# Affiche le bouton « Sponsor » sur la page du depot.
# Decommenter et completer les plateformes utilisees.
github: [achedon12]
# ko_fi: mon-compte
# buy_me_a_coffee: mon-compte
# liberapay: mon-compte
# custom: ["https://leoderoin.fr"]
