import type { Metadata } from "next";
import type { Article } from "@/lib/types";
import { site } from "@/lib/site";
import { LOCALES, DEFAULT_LOCALE, LOCALE_HTML, type Locale } from "./config";

/**
 * A page's language metadata: its canonical (in the current language) and
 * its `hreflang` (one entry per language, plus `x-default`). To be passed to
 * `alternates` in the `generateMetadata` of every translated page.
 *
 * Language codes alone (`fr`, `es`), without region: `fr-FR` or `es-ES` only
 * targeted France and Spain, whereas MLBB's audience is mostly
 * Latin American in Spanish, and African, Belgian or Canadian in French.
 */
export function metaLocales(locale: Locale, path: string) {
  const languages: Record<string, string> = Object.fromEntries(LOCALES.map((l) => [l, `/${l}${path}`]));
  languages["x-default"] = `/${DEFAULT_LOCALE}${path}`;
  return { canonical: `/${locale}${path}`, languages };
}

/**
 * Structured data of a post — news or patch analysis —, in the
 * page's language: `inLanguage` used to announce French everywhere.
 */
export function postData(a: Article, path: string, locale: Locale) {
  return {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: a.title,
    description: a.summary,
    datePublished: a.date,
    dateModified: a.date,
    inLanguage: LOCALE_HTML[locale],
    keywords: a.keywords.join(", "),
    author: { "@type": "Person", name: a.author, url: `https://github.com/${a.author}` },
    publisher: { "@type": "Organization", name: site.name, url: site.url },
    mainEntityOfPage: `${site.url}/${locale}${path}`,
  };
}

/** Open Graph locale of each site language. */
export const OG_LOCALE: Record<Locale, string> = {
  en: "en_US",
  fr: "fr_FR",
  it: "it_IT",
  es: "es_ES",
  id: "id_ID",
};

/**
 * Structured data of a tool (draft, comparator, calculator): a
 * free web application, no account needed, in the page's language.
 */
export function dataTool(
  locale: Locale,
  o: { name: string; description: string; path: string; category: "GameApplication" | "UtilitiesApplication" },
) {
  return {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: o.name,
    description: o.description,
    url: `${site.url}/${locale}${o.path}`,
    applicationCategory: o.category,
    operatingSystem: "Any",
    browserRequirements: "Requires JavaScript",
    inLanguage: LOCALE_HTML[locale],
    isAccessibleForFree: true,
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    publisher: { "@type": "Organization", name: site.name, url: site.url },
    about: { "@type": "VideoGame", name: "Mobile Legends: Bang Bang", publisher: "Moonton" },
  };
}

/**
 * Structured data of a page that lists heroes (catalog, tier list):
 * the page, its update date, and the ordered list of its heroes, each
 * with its hero page address.
 */
export function heroListData(
  locale: Locale,
  o: {
    name: string;
    description: string;
    path: string;
    heroes: { name: string; slug: string }[];
    /** ISO update date of the displayed data. */
    changed?: string;
    /** True when the order is a ranking, from strongest to weakest. */
    ranked?: boolean;
  },
) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: o.name,
    description: o.description,
    url: `${site.url}/${locale}${o.path}`,
    inLanguage: LOCALE_HTML[locale],
    ...(o.changed ? { dateModified: o.changed } : {}),
    isPartOf: { "@type": "WebSite", name: site.name, url: site.url },
    mainEntity: {
      "@type": "ItemList",
      name: o.name,
      numberOfItems: o.heroes.length,
      ...(o.ranked ? { itemListOrder: "https://schema.org/ItemListOrderDescending" } : {}),
      itemListElement: o.heroes.map((h, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: h.name,
        url: `${site.url}/${locale}/heroes/${h.slug}`,
      })),
    },
  };
}

/** Default share image, generated by `src/app/opengraph-image.tsx`. */
const SHARE_IMAGE = { url: "/opengraph-image", width: 1200, height: 630, alt: site.title };

/**
 * Beyond this, the title completed with the site name ("… — MLBBDex") would be cut
 * in the results: the page title then goes alone, without the brand.
 */
const TITLE_MAX = 60;

/**
 * A page's metadata: title, description, canonical and `hreflang`, Open
 * Graph card and Twitter card, always with an image. A page that defines
 * its own `openGraph` replaces the template's, image included: without
 * an explicit image, its shared links were shown bare.
 */
export function metaPage(
  locale: Locale,
  o: {
    title: string;
    description: string;
    /** Path without language, "/heroes/aamon". */
    path: string;
    /** Share card description, if it differs. */
    share?: string;
    /** Page-specific image; otherwise, the site's share image. */
    image?: string;
    type?: "website" | "article";
    keywords?: string[];
    /** An article's publication date. */
    published?: string;
    author?: string;
  },
): Metadata {
  const images = [o.image ? { url: o.image } : SHARE_IMAGE];
  const titleShare = `${o.title} — ${site.name}`;
  const descriptionShare = o.share ?? o.description;
  const openGraph = {
    type: o.type ?? "website",
    siteName: site.name,
    locale: OG_LOCALE[locale],
    title: titleShare,
    description: descriptionShare,
    url: `/${locale}${o.path}`,
    images,
    ...(o.type === "article" && o.published
      ? { publishedTime: o.published, authors: o.author ? [o.author] : undefined }
      : {}),
  } as Metadata["openGraph"];
  return {
    // The layout template appends "— MLBBDex"; an already long title
    // drops it rather than having its end truncated (patch, month).
    title: titleShare.length > TITLE_MAX ? { absolute: o.title } : o.title,
    description: o.description,
    ...(o.keywords?.length ? { keywords: o.keywords } : {}),
    alternates: metaLocales(locale, o.path),
    openGraph,
    twitter: {
      card: "summary_large_image",
      title: titleShare,
      description: descriptionShare,
      images: images.map((i) => i.url),
    },
  };
}
